Add ReplyTo option in MailjetEmailMessage
YieldStudio/laravel-mailjet-notifier pull request #6
Opened 2023-09-02 10:18 UTC by luluni83

Mailjet API allows to customise ReplyTo field in a message. Could be sometimes useful specially for contact form notifications.

2023-09-05 09:22 UTC, dtangdev requested changes

2023-09-05 09:22 UTC, dtangdev commented on src/MailjetEmailMessage.php
> +        if (filled($this->replyto)) {
issue: replace replyto by replyTo

2023-09-05 09:23 UTC, dtangdev commented
Thank you for your changes, good job :)

2023-09-05 09:41 UTC, luluni83 commented on src/MailjetEmailMessage.php
> +        if (filled($this->replyto)) {
Exact

2023-09-07 08:49 UTC, dtangdev approved these changes

2023-09-07 08:50 UTC, merged